export const importantDays = {
  "01-01": "New Year's Day",
  "01-04": "World Braille Day",
  "01-24": "International Day of Education",
  "01-26": "Republic Day (India) & International Day of Clean Energy",
  "01-27": "International Holocaust Remembrance Day",
  "01-28": "International Day of Peaceful Coexistence",
  "02-02": "World Wetlands Day",
  "02-04": "World Cancer Day",
  "02-11": "International Day of Women and Girls in Science",
  "02-13": "World Radio Day",
  "02-20": "World Day of Social Justice",
  "02-21": "International Mother Language Day",
  "03-03": "World Wildlife Day",
  "03-08": "International Women's Day",
  "03-14": "International Day of Mathematics",
  "03-20": "International Day of Happiness",
  "03-21": "International Day of Forests",
  "03-22": "World Water Day",
  "03-24": "World Tuberculosis Day",
  "03-30": "International Day of Zero Waste",
  "04-02": "World Autism Awareness Day",
  "04-06": "International Day of Sport for Development and Peace",
  "04-07": "World Health Day",
  "04-15": "Vishu (Kerala New Year) 🌼",
  "04-22": "International Mother Earth Day",
  "04-23": "World Book and Copyright Day",
  "04-25": "World Malaria Day",
  "04-26": "World Intellectual Property Day & Thrissur Pooram",
  "04-30": "International Jazz Day",
  "05-01": "International Workers' Day / Labour Day",
  "05-02": "International Drone Day",
  "05-03": "World Press Freedom Day",
  "05-08": "World Red Cross Day",
  "05-12": "International Nurses Day",
  "05-15": "International Day of Families",
  "05-20": "World Bee Day",
  "05-22": "International Day for Biological Diversity",
  "05-31": "World No Tobacco Day",
  "06-01": "Global Day of Parents",
  "06-03": "World Bicycle Day",
  "06-05": "World Environment Day",
  "06-08": "World Oceans Day",
  "06-12": "World Day Against Child Labour",
  "06-14": "World Blood Donor Day",
  "06-20": "World Refugee Day",
  "06-21": "International Day of Yoga",
  "06-23": "UN Public Service Day",
  "06-24": "International Day of Women in Diplomacy",
  "06-25": "Day of the Seafarer",
  "06-26": "International Day against Drug Abuse",
  "07-11": "World Population Day",
  "07-15": "World Youth Skills Day",
  "07-18": "Nelson Mandela International Day",
  "07-20": "World Chess Day & International Moon Day",
  "07-28": "World Hepatitis Day",
  "07-30": "International Day of Friendship",
  "08-01": "World Breastfeeding Week (Aug 1-7)",
  "08-09": "International Day of Indigenous Peoples",
  "08-12": "International Youth Day & Athachamayam (Kerala Onam celebrations begin) 🌺",
  "08-15": "Independence Day (India)",
  "08-16": "Thiruvonam (Main Onam Day) 🌼🍛",
  "08-19": "World Humanitarian Day",
  "08-26": "Pulikali, Thrissur 🐯",
  "08-29": "Aranmula Boat Race 🚣 & International Day against Nuclear Tests",
  "09-01": "Manarcad Perunnal (Kottayam) ⛪ (Sep 1-8)",
  "09-05": "Teachers' Day (India) & International Day of Charity",
  "09-08": "International Literacy Day",
  "09-15": "International Day of Democracy",
  "09-16": "World Ozone Day",
  "09-21": "International Day of Peace",
  "09-27": "World Tourism Day",
  "10-01": "International Coffee Day & International Day of Older Persons",
  "10-02": "International Day of Non-Violence & Gandhi Jayanti",
  "10-05": "World Teachers' Day",
  "10-10": "World Mental Health Day",
  "10-11": "International Day of the Girl Child",
  "10-16": "World Food Day",
  "10-17": "International Day for the Eradication of Poverty",
  "10-24": "United Nations Day",
  "11-01": "Kerala Piravi (Kerala Formation Day) 🌴",
  "11-02": "International Day to End Impunity for Crimes against Journalists",
  "11-05": "World Tsunami Awareness Day",
  "11-10": "World Science Day for Peace and Development",
  "11-14": "Children's Day (India) & World Diabetes Day",
  "11-19": "World Toilet Day",
  "11-20": "Universal Children's Day",
  "11-25": "International Day for the Elimination of Violence against Women",
  "12-01": "World AIDS Day",
  "12-03": "International Day of Persons with Disabilities",
  "12-05": "International Volunteer Day",
  "12-07": "International Civil Aviation Day",
  "12-09": "International Anti-Corruption Day",
  "12-10": "Human Rights Day",
  "12-11": "International Mountain Day",
  "12-18": "International Migrants Day",
  "12-20": "International Human Solidarity Day",
  "12-25": "Christmas"
};

export const companyHolidays = {
  "01-02": "Mannam Jayanthi",
  "01-26": "Republic Day",
  "03-20": "Id-ul-Fitr (Ramzan)",
  "04-02": "Maundy Thursday",
  "04-03": "Good Friday",
  "04-14": "Dr. B. R. Ambedkar Jayanthi",
  "04-15": "Vishu",
  "05-01": "May Day",
  "05-27": "Bakrid",
  "06-26": "Muharram",
  "08-12": "Karkidaka Vavu",
  "08-15": "Independence Day",
  "08-25": "First Onam / Milad-un-Nabi",
  "08-26": "Thiruvonam",
  "08-27": "Third Onam",
  "08-28": "Sree Narayana Guru Jayanthi / Ayyankali Jayanthi",
  "09-04": "Sreekrishna Jayanthi",
  "09-21": "Sree Narayana Guru Samadhi",
  "10-02": "Gandhi Jayanti",
  "10-20": "Mahanavami",
  "10-21": "Vijayadasami",
  "12-25": "Christmas"
};
